---
# Source: tigera-operator/templates/crs/custom-resources.yaml
apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: default
spec:
  {}
---
# Source: tigera-operator/templates/crs/custom-resources.yaml
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  imagePath: 192.168.56.1:5000
  imagePullSecrets: []
  kubernetesProvider: ""
